import Reference from 'bible-reference-toolkit'

export const getBookIdFromBookName = (
  bookName: string,
  languageCode: string = 'en'
): number => {
  try {
    console.debug('get book id first time', bookName, languageCode)
    return Reference.bookIdFromTranslationAndName(languageCode, bookName)
  } catch {
    try {
      // try in slow but in all supported languages
      console.debug('get book id from all translations', bookName)
      return Reference.bookIdFromName(bookName)
    } catch {
      // Handle fullNames like "1 사무엘상" generated by non-English numbered books.
      // The library's ordinal-variation logic strips original abbreviations, so the
      // fullName with a leading digit (e.g. "1 사무엘상") can't be found via bookIdFromName.
      // Strip the leading "1/2/3 " prefix and retry.
      const withoutPrefix = bookName.replace(/^[123]\s+/, '')
      if (withoutPrefix !== bookName) {
        console.debug('retrying without number prefix', withoutPrefix)
        return Reference.bookIdFromName(withoutPrefix)
      }
      throw new Error(`No book matched "${bookName}"`)
    }
  }
}

export const getFullBookName = (
  name: string,
  languageCode: string = 'en'
): string => {
  console.debug('getFullBookName', name, languageCode)
  const bookId = getBookIdFromBookName(name, languageCode)

  try {
    return Reference.bookNameFromTranslationAndId(languageCode, bookId)
  } catch {
    return Reference.bookEnglishFullNameFromId(bookId)
  }
}
